name: CI/CD Canary

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  build:
    uses: ./.github/workflows/integrations-test.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      path-secret: PATH_CANARY
      ref: ${{ github.ref_name }}
    secrets: inherit
