name: CI/CD Current

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/integrations-test.yml

  deploy:
    needs: build
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      path-secret: PATH_CURRENT
      ref: main
    secrets: inherit
