name: CI/CD Insider

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/integrations-test.yml

  deploy:
    needs: build
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      path-secret: PATH_INSIDER
      ref: develop
    secrets: inherit
