name: CI/CD Release lapikit

on:
  repository_dispatch:
    types: [lapikit-updated]

jobs:
  build:
    uses: ./.github/workflows/integrations-test.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: current
      ref: main
    secrets: inherit
